
server:
  port: 8083

spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/admin-db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  file: C:/Users/TOSHIBA/Desktop/log-elk/elk-logs.log

info:
  application:
    name: admin-app
    version: '@project.version@'


